# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4a9ba14f8c561781aa177568ec81f5ca12cfed43fd8d464c43a501d5ce533ce095e5009db149130f2743ffbb6f9087f038c37fd60c0bf6e795ed37f865893ca

test:
  secret_key_base: 2e9b0f315779f5739817073b56599fce6dcf2c862ec5dd0a9b363100dcfafe51f954942e1805313a3e49b64b9c5f46dd3759f4b1c3b170578c7bf6e4366ba4e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
